/* ═══════════════════════════════════════════════════════════
   龟龟对战 — 2V2 回合制战斗引擎
   护盾(白条) / 物理伤害(红) / 真实伤害(黄) / 魔法伤害(蓝) / 治疗(绿)
   多段伤害技能 / 持久浮动数字
   ═══════════════════════════════════════════════════════════ */

// ── PET DATABASE ──────────────────────────────────────────
/* Base stats are normalized — rarity bonus applied in createFighter()
   Each rarity tier = +3% to HP/ATK/DEF/SPD over previous tier
   C=1.00  B=1.03  A=1.06  S=1.09  SS=1.12  SSS=1.15
   New stats: crit (暴击率 0~1)
   DEF reduction formula: reduction% = DEF/(DEF+40), diminishing returns
   穿甲: 固定穿甲(armorPen)无视X点防御 + 百分比穿甲(armorPenPct)无视X%防御  */
const RARITY_MULT = { C:1.00, B:1.03, A:1.06, S:1.09, SS:1.12, SSS:1.15 };
const DEF_CONSTANT = 40; // DEF/(DEF+K) formula constant
// 计算有效护甲：先扣百分比穿透，再扣固定穿透
function calcEffArmor(atk, tgt) {
  return Math.max(0, tgt.def * (1 - (atk.armorPenPct || 0)) - (atk.armorPen || 0));
}
// 计算有效魔抗
function calcEffMr(atk, tgt) {
  return Math.max(0, tgt.mr * (1 - (atk.magicPenPct || 0)) - (atk.magicPen || 0));
}
// 根据伤害类型获取有效防御
function calcEffDef(atk, tgt, dmgType) {
  if (dmgType === 'magic') return calcEffMr(atk, tgt);
  if (dmgType === 'true') return 0;
  return calcEffArmor(atk, tgt); // physical or default
}
/* Buff/Debuff effects on skills:
   dot:     { dmg, turns }       — 持续伤害(每回合开始)
   atkDown: { pct, turns }       — 攻击削减(百分比)
   defDown: { pct, turns }       — 防御削减(百分比)
   (spdDown removed — no speed stat)                                    */

// img: path relative to project root (../../assets/pets/...)
// sprite: { frames, frameW, frameH, duration } for animated sprite sheets
const ALL_PETS = [
  // C级 — base stats (crit=暴击率, res按稀有度自动计算)
  // passive: { type, desc, ...params }
  //   bonusDmgAbove60  — 对HP>60%的敌人+X%伤害
  //   deathExplode     — 死亡时对击杀者造成自身最大HP*X%伤害
  //   turnScaleHp      — 每回合+X%最大生命
  //   turnScaleAtk     — 每回合+X%攻击
  //   lowHpCrit        — HP<30%时暴击率+X%
  //   shieldOnHit      — 受击时获得X护盾(每回合1次)
  //   healOnKill       — 击杀时恢复X%最大HP
  //   counterAttack    — X%概率反击(造成基础攻击50%伤害)
  { id:'basic',     name:'小龟',     emoji:'🐢',      rarity:'C',   hp:350,  atk:40,  def:14, mr:13, spd:10, crit:0.25,
    img:'../../assets/pets/基础小龟v1.png', sprite:{frames:8,frameW:64,frameH:64,duration:800},
    passive:{ type:'basicTurtle', name:'不屈', bonusMap:{C:20,B:23,A:26,S:29,SS:32,SSS:34},
              desc:'小龟面对强敌愈战愈勇。攻击时根据目标稀有度获得增伤：\n<span style="color:#06d6a0">C</span> <span class="val-atk">+20%</span>　<span style="color:#4cc9f0">B</span> <span class="val-atk">+23%</span>　<span style="color:#3a9abf">A</span> <span class="val-atk">+26%</span>\n<span style="color:#c77dff">S</span> <span class="val-atk">+29%</span>　<span style="color:#ffd93d">SS</span> <span class="val-atk">+32%</span>　<span style="color:#ff6b6b">SSS</span> <span class="val-atk">+34%</span>' },
    skills:[
      { name:'攻击', type:'physical', hits:2, power:0, pierce:0, cd:0, atkScale:0.7, selfAtkUpPct:{pct:20, turns:2},
        brief:'小龟攻击2段，共{N:0.7*ATK*2}物理伤害，自身攻击+20% 2回合',
        detail:'小龟对单体打击2段，每段 70%×(攻击力={ATK}) = {N:0.7*ATK} 物理伤害，共 140%×(攻击力={ATK}) = {N:0.7*ATK*2}。\n自身攻击+20% 2回合。' },
      { name:'龟盾', type:'turtleShieldBash', hits:1, power:0, pierce:0, cd:2, atkScale:0.7, lostHpPct:20, shieldFromDmgPct:80,
        brief:'小龟造成（{N:0.7*ATK} + 目标已损生命值20%）物理伤害，获得80%伤害值的永久护盾',
        detail:'小龟对单体造成（70%×攻击力({ATK}) = {N:0.7*ATK}）+ 目标已损生命值 <span class="val-atk">20%</span> 物理伤害。\n获得造成伤害 <span class="val-atk">80%</span> 的永久护盾。\n冷却{cd}回合。' },
      { name:'打击', type:'basicBarrage', hits:10, power:0, pierce:0, cd:4, atkScale:2.9,
        brief:'小龟发射10段共{N:2.9*ATK}物理伤害随机分布敌方',
        detail:'小龟对敌方发射10段攻击，随机分布。\n共 290%×(攻击力={ATK}) = {N:2.9*ATK} 物理伤害。\n冷却{cd}回合。' },
    ]},
  { id:'stone',     name:'石头龟',   emoji:'🪨🐢',    rarity:'C',   hp:380,  atk:35,  def:18, mr:15, spd:6, crit:0.25,
    img:'../../assets/pets/石头龟v1.png', sprite:{frames:10,frameW:500,frameH:500,duration:1000},
    passive:{ type:'stoneWall', name:'坚壁', defGain:2, maxDef:16, reflectBase:5, reflectPerDef:1, reflectPerMr:0.5,
              brief:'石头龟越战越硬。每回合永久 <span class="val-def">护甲</span><span class="val-atk">+2</span>（上限<span class="val-atk">+16</span>）；受伤反弹 <span class="val-atk">{N:5+DEF+MR*0.5}%</span> 伤害',
              desc:'石头龟越战越硬。\n\n每回合永久增加 <span class="val-def">护甲</span> <span class="val-atk">+2</span>（上限 <span class="val-atk">+16</span>，已叠加 <span class="val-atk">+{stoneDefGained}</span>）\n\n受到伤害时反弹：\n5% + 1%×<span class="val-def">护甲</span>({DEF}) + 0.5%×<span class="val-magic">魔抗</span>({MR}) = <span class="val-atk">{N:5+DEF+MR*0.5}%</span> 伤害' },
    skills:[
      { name:'打击',     type:'physical', hits:2, power:0, pierce:0, cd:0, atkScale:0.35, defScale:0.7, mrScale:0.4,
        brief:'石头龟打击2段，共 {N:0.35*ATK*2}+{D:0.7*DEF*2}+{M:0.4*MR*2} 物理伤害',
        detail:'石头龟对单体目标打击2段，每段造成（35%×攻击力({ATK}) = {N:0.35*ATK}）+（70%×护甲({DEF}) = {D:0.7*DEF}）+（40%×魔抗({MR}) = {M:0.4*MR}）物理伤害。\n共 {N:0.35*ATK*2}+{D:0.7*DEF*2}+{M:0.4*MR*2} 物理伤害。' },
      { name:'岩石护甲', type:'shield', hits:1, power:0, shield:0, cd:3, aoeAlly:true, shieldFlat:14, shieldHpPct:10, shieldDuration:3,
        brief:'石头龟为全体友军施加{S:14+HP*0.1}护盾，持续3回合',
        detail:'石头龟为全体友军施加护盾，14 + 10%×最大生命值({HP}) = {S:14+HP*0.1} 护盾，持续3回合。\n冷却{cd}回合。' },
      { name:'磐石',     type:'heal', hits:1, power:0, heal:0, cd:4, defUpPct:{pct:20,turns:3}, mrUpPct:{pct:20,turns:3},
        brief:'石头龟强化一名友方，提升护甲 {D:DEF*0.2} 和魔抗 {M:MR*0.2}，持续3回合',
        detail:'石头龟选择一名友方，以自身的防御属性为其加固：\n提升护甲（20%×护甲({DEF}) = {D:DEF*0.2}）持续3回合\n提升魔抗（20%×魔抗({MR}) = {M:MR*0.2}）持续3回合\n冷却{cd}回合。' },
    ]},
  { id:'bamboo',    name:'竹叶龟',   emoji:'🎋🐢',    rarity:'C',   hp:300,  atk:40,  def:10, mr:11, spd:12, crit:0.25,
    img:'../../assets/pets/竹叶龟v1.png', sprite:{frames:10,frameW:500,frameH:400,duration:1000},
    passive:{ type:'bambooCharge', name:'生长', atkPct:85, selfHpPct:12, healSelfHpPct:8, hpGainAtkPct:45, chargeDmgType:'magic',
              brief:'每隔1回合充能<img src="assets/bamboo-charge-icon.png" class="stat-icon">，充能完毕时，技能释放后追加一发强化普攻：\n\n造成 {M:ATK*0.85+HP*0.12} 魔法伤害\n回复 {H:HP*0.08} <span class="val-heal">HP</span>\n永久增加 {H:ATK*0.45} <span class="val-heal">最大生命值</span>',
              desc:'竹叶龟每隔1回合充能被动<img src="assets/bamboo-charge-icon.png" class="stat-icon">「生长」，充能完毕时，技能释放后追加一发强化普攻：\n\n造成 {M:ATK*0.85+HP*0.12} 魔法伤害（85%攻击力 + 12%<span class="val-heal">最大HP</span>）\n回复 {H:HP*0.08} <span class="val-heal">HP</span>（8%<span class="val-heal">最大HP</span>）\n永久增加 {H:ATK*0.45} <span class="val-heal">最大生命值</span>（45%攻击力）\n\n已通过被动累计获得 {H:bambooGainedHp} <span class="val-heal">最大生命值</span>' },
    skills:[
      { name:'一叶刃', type:'bambooLeaf', hits:3, power:0, pierce:0, cd:0, atkScale:0.21, selfHpPct:6,
        brief:'竹叶龟甩出3片叶刃，每段{N:0.21*ATK}+6%最大HP物理伤害',
        detail:'竹叶龟对单体甩出3片叶刃。\n每段造成 21%×(攻击力={ATK}) = {N:0.21*ATK} + 6%×(最大HP={HP}) = {N:HP*0.06} 物理伤害。\n共 {N:0.21*ATK*3+HP*0.06*3} 物理伤害。' },
      { name:'自然恢复', type:'bambooHeal', hits:1, power:0, pierce:0, cd:3, healPct:10, shieldPct:12, shieldTurns:3, soloHealPct:15,
        brief:'竹叶龟回复{H:HP*0.1}HP，队友获得{S:HP*0.12}护盾3回合（无队友则回复{H:HP*0.15}）',
        detail:'竹叶龟回复 10%×(最大HP={HP}) = {H:HP*0.1} HP。\n为存活队友施加 12%×(最大HP={HP}) = {S:HP*0.12} 护盾，持续3回合。\n如果没有存活队友，改为回复 15%×(最大HP={HP}) = {H:HP*0.15} HP。\n冷却{cd}回合。' },
    ]},
  // B级
  { id:'angel',     name:'天使龟',   emoji:'😇🐢',    rarity:'B',   hp:340,  atk:41,  def:13, mr:16, spd:11, crit:0.25,
    img:'../../assets/pets/天使龟v1.png', sprite:{frames:8,frameW:248,frameH:200,duration:800},
    passive:{ type:'judgement', name:'审判', hpPct:9, desc:'每段攻击附带目标当前9%HP的魔法伤害' },
    skills:[
      { name:'裁决', type:'physical', hits:4, power:0, pierce:0, cd:0, atkScale:0.3,
        brief:'天使龟对单体敌人裁决4段，共造成 {N:0.3*ATK*4} 物理伤害',
        detail:'天使龟对单体打击4段，每段 30%×(攻击力={ATK}) = {N:0.3*ATK} 物理伤害，共 120%×(攻击力={ATK}) = {N:0.3*ATK*4} 物理伤害。' },
      { name:'祝福', type:'angelBless', dmgType:'magic', hits:1, power:0, pierce:0, cd:4, shieldScale:1.2, shieldTurns:4, defBoostScale:0.12, defBoostTurns:4,
        brief:'天使龟选择一名友方单位，使其获得持续{shieldTurns}回合的{S:1.2*ATK}护盾值 + 持续{defBoostTurns}回合的{D:0.12*ATK}点<span class="val-def">护甲</span>与<span class="val-magic">魔抗</span>提升',
        detail:'天使龟选择友方单体，施加 120%×(攻击力={ATK}) = {S:1.2*ATK} 护盾，持续{shieldTurns}回合。\n同时增加<span class="val-def">护甲</span>与<span class="val-magic">魔抗</span> 12%×(攻击力={ATK}) = {D:0.12*ATK}点，持续{defBoostTurns}回合。\n冷却{cd}回合。' },
      { name:'平等', type:'angelEquality', dmgType:'magic', hits:2, power:0, pierce:0, cd:5, normalScale:0.6, pierceScale:0.6,
        antiHighRarity:['S','SS'], forceCrit:true, healPctOfDmg:10,
        brief:'天使龟对单体打击两段，分别造成 {M:0.6*ATK} 魔法伤害和 {T:0.6*ATK} 真实伤害，如果目标是S级及以上则两段攻击必定暴击并回复造成伤害的10%<span class="val-heal">生命值</span>',
        detail:'天使龟对单体打击两段：\n第一段造成 60%×(攻击力={ATK}) = {M:0.6*ATK} 魔法伤害\n第二段造成 60%×(攻击力={ATK}) = {T:0.6*ATK} 真实伤害\n\n如果目标为S级及以上，则两段打击必定暴击，并回复总伤害的10%<span class="val-heal">生命值</span>。\n冷却{cd}回合。' },
    ]},
  { id:'ice',       name:'寒冰龟',   emoji:'❄️🐢',    rarity:'B',   hp:381,  atk:39,  def:16, mr:18, spd:9, crit:0.25,
    img:'../../assets/pets/寒冰龟.png',
    passive:{ type:'frostAura', name:'冰寒', atkDownPct:20, atkDownTurns:6, burnImmune:true,
              bonusTargets:['lava','phoenix'], bonusDmgPct:35,
              brief:'开局敌方全体攻击力 <span class="val-atk">-20%</span> 6回合。免疫<span style="color:#ff6600">灼烧</span>。对火系龟额外 <span class="val-atk">+35%</span> 伤害',
              desc:'寒冰龟登场时，敌方全体攻击力 <span class="val-atk">-20%</span>，持续6回合。\n寒冰龟免疫<span style="color:#ff6600">灼烧</span>效果。\n对熔岩龟/凤凰龟造成额外 <span class="val-atk">+35%</span> 伤害。' },
    skills:[
      { name:'冰锥', type:'iceSpike', hits:6, power:0, pierce:0, cd:0, totalScale:1.4,
        brief:'寒冰龟发射6段冰锥，交替造成物理伤害和魔法伤害，共 {N:1.4*ATK*0.5} 物理伤害和 {M:1.4*ATK*0.5} 魔法伤害',
        detail:'寒冰龟对单体发射6段冰锥，奇数段造成 23%×(攻击力={ATK}) = {N:1.4*ATK/6} 物理伤害，偶数段造成 23%×(攻击力={ATK}) = {M:1.4*ATK/6} 魔法伤害。\n共 70%×(攻击力={ATK}) = {N:1.4*ATK*0.5} 物理伤害 + 70%×(攻击力={ATK}) = {M:1.4*ATK*0.5} 魔法伤害。' },
      { name:'冰盾', type:'iceShield', hits:1, power:0, pierce:0, cd:2, selfScale:1.4, allyScale:0.8,
        brief:'寒冰龟自身获得{S:1.4*ATK}永久护盾，友方获得{S:0.8*ATK}永久护盾',
        detail:'寒冰龟为自身施加 140%×(攻击力={ATK}) = {S:1.4*ATK} 永久护盾。\n为友方施加 80%×(攻击力={ATK}) = {S:0.8*ATK} 永久护盾。\n冷却{cd}回合。' },
      { name:'冰霜', type:'iceFrost', dmgType:'magic', hits:10, power:0, pierce:0, cd:4, atkScale:0.16, mrDown:{pct:25,turns:4},
        brief:'寒冰龟先削减全体敌方 <span class="val-atk">-25%</span> 魔抗，再造成10段共 {M:0.16*ATK*10} 魔法伤害',
        detail:'寒冰龟释放冰霜，先削减全体敌方魔抗 <span class="val-atk">-25%</span>，持续4回合。\n随后对全体敌方同时造成10段伤害，每段（16%×攻击力({ATK}) = {M:0.16*ATK}）魔法伤害。\n共（160%×攻击力({ATK}) = {M:0.16*ATK*10}）魔法伤害。\n冷却{cd}回合。' },
    ]},
  { id:'ninja',     name:'忍者龟',   emoji:'🥷🐢',    rarity:'B',   hp:319,  atk:47,  def:9,  mr:7, spd:15, crit:0.25,
    img:'../../assets/pets/忍者龟.png',
    passive:{ type:'ninjaInstinct', name:'忍术', critBonus:45, critDmgBonus:20, armorPen:8,
              desc:'忍者龟天生忍术精通。开局永久获得：暴击率 <span class="val-atk">+45%</span>，暴击伤害 <span class="val-atk">+20%</span>，护甲穿透 <span class="val-atk">+8</span>' },
    skills:[
      { name:'飞镖',     type:'ninjaShuriken', hits:1, power:0, pierce:0, cd:0, atkScale:1.5,
        brief:'忍者龟投掷飞镖造成（{N:1.5*ATK}）物理伤害，暴击时转为真实伤害',
        detail:'忍者龟对单体投掷飞镖，造成（150%×攻击力({ATK}) = {N:1.5*ATK}）物理伤害。\n暴击时，全部伤害转为真实伤害，并乘以暴击倍率。' },
      { name:'陷阱',     type:'ninjaTrap', hits:1, power:0, pierce:0, cd:3, trapScale:1.8,
        brief:'忍者龟在友方布置夹子，被攻击时触发（{N:1.8*ATK}）物理伤害',
        detail:'忍者龟在一名友方身上布置隐形夹子（对手不可见）。\n该友方被攻击时触发，对攻击者造成（180%×攻击力({ATK}) = {N:1.8*ATK}）物理伤害，一次性消耗。\n冷却{cd}回合。' },
      { name:'炸弹',     type:'ninjaBomb', hits:1, power:0, pierce:0, cd:4, atkScale:1.1, armorBreak:{pct:25,turns:3},
        brief:'忍者龟对全体敌方造成（{N:1.1*ATK}）物理伤害，施加 <span class="val-atk">-25%护甲</span> 效果3回合',
        detail:'忍者龟对全体敌方造成（110%×攻击力({ATK}) = {N:1.1*ATK}）物理伤害。\n对所有命中目标施加 <span class="val-atk">-25%</span> 护甲削减效果，持续3回合。\n冷却{cd}回合。' },
    ]},
  { id:'two_head',  name:'双头龟',   emoji:'🐢🐢',    rarity:'B',   hp:302,  atk:50,  def:11, mr:12, spd:7, crit:0.25,
    img:'../../assets/pets/双头龟.png',
    passive:{ type:'twoHeadDual', name:'双生', hpScale:1.5, defScale:0.25, atkLossScale:0.3, shieldScale:1.1,
              brief:'双头龟可在远程和近战形态间切换，切换时属性变化',
              desc:'双头龟拥有双生之力，可在远程和近战形态间切换。\n\n切换近战时：\n最大生命值增加（150%×攻击力({ATK}) = {H:ATK*1.5}）\n护甲增加（25%×攻击力({ATK}) = {D:ATK*0.25}）\n攻击力降低（30%×攻击力({ATK}) = {N:ATK*0.3}）\n获得（110%×攻击力({ATK}) = {S:ATK*1.1}）护盾\n\n切换远程时还原所有属性，并对目标造成伤害+减护甲。',
              descMelee:'双头龟拥有双生之力，当前为近战形态。\n\n切换远程时：\n属性还原为远程形态\n对目标造成（140%×攻击力({ATK}) = {N:ATK*1.4}）物理伤害\n削减目标护甲（10%×攻击力({ATK}) = {D:ATK*0.1}）持续4回合' },
    // 远程技能组（默认）
    skills:[
      { name:'魔法波', type:'twoHeadMagicWave', hits:4, power:0, pierce:0, cd:0, atkScale:0.4,
        brief:'双头龟发射4段，物理/真实交替，共（{N:0.4*ATK*4}）混合伤害',
        detail:'双头龟对单体发射4段魔法波。\n奇数段造成（40%×攻击力({ATK}) = {N:0.4*ATK}）物理伤害。\n偶数段造成（40%×攻击力({ATK}) = {T:0.4*ATK}）真实伤害。\n共（160%×攻击力({ATK}) = {N:0.4*ATK*4}）混合伤害。' },
      { name:'灵能冲击', type:'physical', hits:1, power:0, pierce:0, cd:4, aoe:true, atkScale:0.85, hpPct:15,
        brief:'双头龟对全体敌方造成（{N:0.85*ATK}）+ 15%目标最大生命值 物理伤害',
        detail:'双头龟对全体敌方造成（85%×攻击力({ATK}) = {N:0.85*ATK}）+ 15%目标最大生命值 物理伤害。\n冷却{cd}回合。' },
      { name:'切换近战', type:'twoHeadSwitch', hits:1, power:0, pierce:0, cd:4, switchTo:'melee', switchAtkScale:1.2,
        brief:'切换近战：+{H:ATK*1.5}HP +{D:ATK*0.25}护甲 -{N:ATK*0.3}攻击力，获得{S:ATK*1.1}护盾，并造成（{N:ATK*1.2}）物理伤害',
        detail:'双头龟切换为近战形态。\n最大生命值增加（150%×攻击力({ATK}) = {H:ATK*1.5}）\n护甲增加（25%×攻击力({ATK}) = {D:ATK*0.25}）\n攻击力降低（30%×攻击力({ATK}) = {N:ATK*0.3}）\n获得（110%×攻击力({ATK}) = {S:ATK*1.1}）护盾\n并对目标造成（120%×攻击力({ATK}) = {N:ATK*1.2}）物理伤害。\n冷却{cd}回合。' },
    ],
    // 近战技能组（切换后替换）
    meleeSkills:[
      { name:'锤击', type:'twoHeadHammer', hits:1, power:0, pierce:0, cd:0, atkScale:1.4, shieldFromDmgPct:50,
        brief:'双头龟锤击造成（{N:1.4*ATK}）物理伤害，获得50%造成伤害的永久护盾',
        detail:'双头龟对单体锤击，造成（140%×攻击力({ATK}) = {N:1.4*ATK}）物理伤害。\n获得造成伤害 <span class="val-atk">50%</span> 的永久护盾。' },
      { name:'吸收', type:'twoHeadAbsorb', hits:1, power:0, pierce:0, cd:2, atkScale:0.6, hpPct:8, healAtkPct:40, healLostPct:18,
        brief:'双头龟造成（{N:0.6*ATK}）+ 8%目标最大生命值 物理伤害，回复（{H:ATK*0.4}）+ <span class="val-heal">18%</span> 已损生命值',
        detail:'双头龟对单体造成（60%×攻击力({ATK}) = {N:0.6*ATK}）+ 8%目标最大生命值 物理伤害。\n回复（40%×攻击力({ATK}) = {H:ATK*0.4}）+ <span class="val-heal">18%</span> 已损生命值。\n冷却{cd}回合。' },
      { name:'切换远程', type:'twoHeadSwitch', hits:1, power:0, pierce:0, cd:4, switchTo:'ranged', atkScale:1.4, defReductionScale:0.25, defReductionTurns:4,
        brief:'切换远程并造成（{N:ATK*1.4}）物理伤害，削减目标护甲（{D:ATK*0.25}）4回合',
        detail:'双头龟切换为远程形态，还原所有属性。\n对目标造成（140%×攻击力({ATK}) = {N:ATK*1.4}）物理伤害。\n削减目标护甲（25%×攻击力({ATK}) = {D:ATK*0.25}）持续4回合。\n冷却{cd}回合。' },
    ],
  },
  { id:'ghost',     name:'幽灵龟',   emoji:'👻🐢',    rarity:'B',   hp:309,  atk:43,  def:9,  mr:11, spd:14, crit:0.25,
    img:'../../assets/pets/幽灵龟v1.png', sprite:{frames:17,frameW:500,frameH:500,duration:1700},
    passive:{ type:'ghostCurse', hpPct:10, turns:3, desc:'死亡时诅咒全体敌人3回合，每回合受到10%目标最大HP的真实持续伤害' },
    skills:[
      { name:'幽魂触碰', type:'ghostTouch', hits:1, power:0, pierce:0, cd:0, normalScale:0.5, pierceScale:1.0,
        brief:'灵体攻击：{N:0.5*ATK}物理 + {P:ATK}真实',
        detail:'幽灵龟用灵体触碰敌人。\n造成 50%×(攻击力={ATK}) = {N:0.5*ATK} 物理伤害\n+ 100%×(攻击力={ATK}) = {P:ATK} 真实伤害。' },
      { name:'虚化', type:'ghostPhase', hits:1, power:0, pierce:0, cd:3, shieldScale:0.8, dodgePct:60, dodgeTurns:2,
        brief:'虚化：{dodgePct}%闪避{dodgeTurns}回合 + {S:0.8*ATK}护盾',
        detail:'幽灵龟身体虚化。\n获得 {dodgePct}% 闪避率，持续{dodgeTurns}回合。\n同时获得 80%×(攻击力={ATK}) = {S:0.8*ATK} 护盾。\n冷却{cd}回合。' },
      { name:'灵魂风暴', type:'ghostStorm', dmgType:'true', hits:5, power:0, pierce:0, cd:4, pierceScale:0.35, dotScale:0.1, dotTurns:3,
        brief:'对单体5段真实共{P:0.35*ATK*5}，附加诅咒3回合（每回合{D:0.1*ATK}）',
        detail:'幽灵龟对单体目标释放灵魂风暴。\n每段造成 {P:0.35*ATK} 真实伤害（35%攻击力）。\n5段共 {P:0.35*ATK*5} 真实伤害。\n附加诅咒3回合：每回合 {D:0.1*ATK} 持续伤害（10%攻击力）。\n冷却{cd}回合。' },
    ]},
  { id:'diamond',   name:'钻石龟',   emoji:'💎🐢',    rarity:'B',   hp:361,  atk:36,  def:21, mr:18, spd:8, crit:0.25,
    img:'../../assets/pets/钻石龟.png',
    passive:{ type:'diamondStructure', name:'钻石结构', defBuffAmp:50, flatReductionPct:15,
              brief:'全队护甲/魔抗加成额外 <span class="val-atk">+50%</span>；每段受伤固定减免 {D:DEF*0.15}（真实伤害除外）',
              desc:'钻石龟的结构强化全队防御体系。\n\n全队所有护甲和魔抗加成效果额外放大 <span class="val-atk">+50%</span>\n\n每段受到伤害时固定减免（15%×护甲({DEF}) = {D:DEF*0.15}）伤害\n真实伤害不受此减免影响。' },
    skills:[
      { name:'钻石切割', type:'physical', hits:1, power:0, pierce:0, cd:0, atkScale:0.7, defScale:0.6, mrScale:0.6,
        brief:'钻石龟切割敌方，造成（{N:0.7*ATK}+{D:0.6*DEF}+{M:0.6*MR}）物理伤害',
        detail:'钻石龟对单体切割，造成（70%×攻击力({ATK}) = {N:0.7*ATK}）+（60%×护甲({DEF}) = {D:0.6*DEF}）+（60%×魔抗({MR}) = {M:0.6*MR}）物理伤害。\n防御属性越高伤害越高。' },
      { name:'坚不可摧', type:'diamondFortify', hits:1, power:0, pierce:0, cd:3, shieldHpPct:20, shieldTurns:3, defUpAtkPct:20, mrUpAtkPct:20, defUpTurns:3,
        brief:'钻石龟获得 {S:HP*0.2} 护盾3回合 + 护甲 {D:ATK*0.2} + 魔抗 {M:ATK*0.2} 3回合',
        detail:'钻石龟凝聚钻石结构自我强化。\n获得（20%×最大生命值({HP}) = {S:HP*0.2}）护盾，持续3回合。\n提升护甲（20%×攻击力({ATK}) = {D:ATK*0.2}）持续3回合。\n提升魔抗（20%×攻击力({ATK}) = {M:ATK*0.2}）持续3回合。\n冷却{cd}回合。' },
      { name:'碰撞', type:'diamondCollide', hits:1, power:0, pierce:0, cd:3, atkScale:0.8, defScale:0.9, mrScale:0.9, selfHpPct:8, stunAfter:2,
        brief:'钻石龟撞击敌方，造成（{N:0.8*ATK}+{D:0.9*DEF}+{M:0.9*MR}+{H:HP*0.08}）物理伤害，累计2次眩晕',
        detail:'钻石龟全身撞击单体，造成（80%×攻击力({ATK}) = {N:0.8*ATK}）+（90%×护甲({DEF}) = {D:0.9*DEF}）+（90%×魔抗({MR}) = {M:0.9*MR}）+（8%×最大生命值({HP}) = {H:HP*0.08}）物理伤害。\n共 {N:0.8*ATK+0.9*DEF+0.9*MR+HP*0.08} 物理伤害。\n同一目标累计被碰撞{stunAfter}次 → 眩晕1回合。\n冷却{cd}回合。' },
    ]},
  { id:'fortune',   name:'财神龟',   emoji:'🧧🐢',    rarity:'B',   hp:340,  atk:39,  def:13, mr:13, spd:10, crit:0.25,
    img:'../../assets/pets/财神龟v1.png', sprite:{frames:18,frameW:500,frameH:500,duration:1800},
    passive:{ type:'fortuneGold', desc:'每回合获得3~8金币，单位阵亡+9金币' },
    skills:[
      { name:'打击',     type:'physical', hits:3, power:0, pierce:0, cd:0, atkScale:0.4,
        brief:'财神龟打击3段，共{N:0.4*ATK*3}物理伤害',
        detail:'每段造成 40%×(攻击力={ATK}) = {N:0.4*ATK} 物理伤害 × 3段 = {N:0.4*ATK*3}' },
      { name:'骰子',     type:'fortuneDice', hits:1, power:0, pierce:0, cd:0, healPct:10,
        brief:'财神龟掷骰子获得3~8枚金币，并回复{H:HP*0.1}HP',
        detail:'财神龟掷骰子获得3~8枚金币，并回复 10%×(最大HP={HP}) = {H:HP*0.1} HP。' },
      { name:'梭哈',     type:'fortuneAllIn', hits:1, power:0, pierce:0, cd:999, perCoinAtkPierce:0.2, perCoinAtkNormal:0.2, oneTimeUse:true,
        brief:'财神龟消耗全部金币（当前{goldCoins}枚），每枚造成{N:ATK*0.2}物理+{P:ATK*0.2}真实伤害（一场限一次）',
        detail:'财神龟消耗全部金币(当前{goldCoins}枚)，每枚造成1段混合伤害：\n20%×(攻击力={ATK}) = {N:ATK*0.2} 物理 + 20%×(攻击力={ATK}) = {P:ATK*0.2} 真实。\n⚠ 一场只能使用一次。' },
    ]},
  { id:'dice',      name:'骰子龟',   emoji:'🎲🐢',    rarity:'B',   hp:330,  atk:41,  def:11, mr:10, spd:11, crit:0.25,
    img:'../../assets/pets/骰子龟v1.png',
    passive:{ type:'gamblerBlood', name:'赌徒之血', maxCritAtLoss:30, maxCritGain:50, overflowMult:1.5,
              brief:'血量越低暴击越高，暴击溢出转为爆伤',
              desc:'骰子龟的赌徒之血在危机中觉醒。\n\n基于已损生命值获得暴击率加成：\n损失30%生命值时达到满额 <span class="val-atk">+50%</span> 暴击率。\n暴击率超过100%的部分，每1%转为 <span class="val-atk">1.5%</span> 暴击伤害。\n\n当前暴击率：<span class="val-atk">{N:crit*100}%</span>' },
    skills:[
      { name:'骰子攻击', type:'diceAttack', hits:3, power:0, pierce:0, cd:0, atkScale:0.9, critBonusMult:55,
        brief:'骰子龟掷3颗骰子，每段（{N:0.3*ATK+crit*55/3}），共（{N:0.9*ATK+crit*55}）物理伤害',
        detail:'骰子龟对单体掷出3颗骰子，共3段。\n每段造成（30%×攻击力({ATK}) = {N:0.3*ATK}）+（暴击率加成 = {N:crit*55/3}）= {N:0.3*ATK+crit*55/3} 物理伤害。\n共（{N:0.9*ATK+crit*55}）物理伤害。' },
      { name:'孤注一掷', type:'diceAllIn', dmgType:'physical', hits:1, power:0, pierce:0, cd:3, atkScale:1.1, lifestealPct:30,
        brief:'骰子龟对全体敌方造成（{N:1.1*ATK}）物理伤害，附带 <span class="val-heal">30%</span> 生命偷取',
        detail:'骰子龟拼命一搏，对每个敌方造成（110%×攻击力({ATK}) = {N:1.1*ATK}）物理伤害。\n本次攻击附带 <span class="val-heal">30%</span> 生命偷取，基于造成的总伤害回复。\n冷却{cd}回合。' },
      { name:'命运骰子', type:'diceFate', hits:0, power:0, pierce:0, cd:5, minCrit:40, maxCrit:130, duration:5,
        brief:'骰子龟获得随机 <span class="val-atk">40%~130%</span> 暴击率提升，持续5回合',
        detail:'骰子龟掷出命运骰子，获得随机 <span class="val-atk">40%~130%</span> 暴击率提升，持续5回合。\n暴击率超过100%的部分，每1%转为 <span class="val-atk">1.5%</span> 暴击伤害。\n冷却{cd}回合。' },
    ]},
  // A级
  { id:'rainbow',   name:'彩虹龟',   emoji:'🌈🐢',    rarity:'A',   hp:360,  atk:42,  def:15, mr:17, spd:13, crit:0.25,
    img:'../../assets/pets/彩虹龟.png',
    passive:{ type:'rainbowPrism', name:'棱镜', atkPct:15, defPct:15, healPct:7,
              desc:'彩虹龟的棱镜每回合折射出随机光芒，为全体友方附加增益1回合：\n🔴红光：攻击力 <span class="val-atk">+15%</span>\n🔵蓝光：护甲 <span class="val-atk">+15%</span> + 魔抗 <span class="val-atk">+15%</span>\n🟢绿光：回复 <span class="val-heal">7%</span> 最大生命值\n\n首回合不会抽到绿光。' },
    skills:[
      { name:'七彩光束', type:'magic', dmgType:'magic', hits:2, power:0, pierce:0, cd:0, atkScale:0.7, prismBonus:true,
        brief:'彩虹龟射出光束2段，共 {M:0.7*ATK*2} 魔法伤害，根据当前棱镜颜色附加效果',
        detail:'彩虹龟射出七彩光束，对单体打击2段。\n每段造成（70%×攻击力({ATK}) = {M:0.7*ATK}）魔法伤害。\n共（140%×攻击力({ATK}) = {M:0.7*ATK*2}）魔法伤害。\n\n根据当前回合棱镜颜色附加效果：\n🔴红光：额外造成20%总伤害的真实伤害\n🔵蓝光：自身获得（20%×攻击力({ATK}) = {S:0.2*ATK}）护盾\n🟢绿光：回复自身 <span class="val-heal">5%</span> 最大生命值' },
      { name:'棱镜护盾', type:'shield', hits:1, power:0, pierce:0, cd:3, shieldAtkScale:0.5, aoeAlly:true,
        brief:'彩虹龟为全体友方施加 {S:0.5*ATK} 护盾',
        detail:'彩虹龟用棱镜之光保护全体友方。\n每人获得（50%×攻击力({ATK}) = {S:0.5*ATK}）护盾。\n冷却{cd}回合。' },
      { name:'全色风暴', type:'rainbowStorm', dmgType:'magic', hits:4, power:0, pierce:0, cd:4, aoe:true, atkScale:0.2, pierceScale:0.1, defDown:{pct:20,turns:3}, burn:true,
        brief:'彩虹龟对全体敌人4段，每段 {M:0.2*ATK} 魔法+{T:0.1*ATK} 真实，施加 <span class="val-atk">-20%护甲</span> + 灼烧4回合',
        detail:'彩虹龟对全体敌人释放七色风暴，共4段。\n每段造成（20%×攻击力({ATK}) = {M:0.2*ATK}）魔法伤害 +（10%×攻击力({ATK}) = {T:0.1*ATK}）真实伤害。\n对所有命中目标施加 <span class="val-atk">-20%</span> 护甲削减效果，持续3回合。\n附加灼烧4回合（每回合40%攻击力+8%最大生命值，魔法伤害）。\n冷却{cd}回合。' },
    ]},
  { id:'gambler',   name:'赌神龟',   emoji:'🃏🐢',    rarity:'A',   hp:329,  atk:47,  def:11, mr:11, spd:14, crit:0.25,
    img:'../../assets/pets/赌神龟v1.png', sprite:{frames:8,frameW:500,frameH:500,duration:800},
    passive:{ type:'gamblerMultiHit', chance:40, dmgScale:0.6, desc:'每段攻击40%概率触发额外 60%×(攻击力={ATK}) = {N:ATK*0.6} 打击（可连锁，递减）' },
    skills:[
      { name:'卡牌射击', type:'gamblerCards', hits:3, power:0, pierce:0, cd:0, minScale:0.3, maxScale:0.6,
        brief:'赌神龟射出3张牌，每段随机造成{N:ATK*0.3}~{N:ATK*0.6}物理伤害，可触发多重打击',
        detail:'赌神龟对单体目标射出3张牌，每段随机造成 30%~60%×(攻击力={ATK}) = {N:ATK*0.3}~{N:ATK*0.6} 物理伤害。\n每段可触发多重打击被动。' },
      { name:'抽牌',     type:'gamblerDraw', hits:1, power:0, pierce:0, cd:2,
        brief:'赌神龟随机抽一张牌：回复牌、炸弹牌或强化牌',
        detail:'赌神龟随机抽一张牌：\n💚回复牌：回复10%HP + 5%HP护盾\n💥炸弹牌：全体敌方 90%×(攻击力={ATK}) = {N:ATK*0.9} 伤害\n⚡强化牌：+15%ATK +25%暴击 +15%爆伤 +20%伤害转真实 3回合\n冷却{cd}回合。' },
      { name:'赌注',     type:'gamblerBet', hits:6, power:0, pierce:0, cd:4, hpCostPct:50, multiBonus:20,
        brief:'赌神龟消耗50%当前HP化为6段强化攻击，多重打击概率提升至60%（需HP>50%）',
        detail:'赌神龟消耗当前50%HP，化为对单体目标的6段强化攻击。\n消耗的HP均分为每段真实伤害加成。多重打击概率从40%提升至60%。\n需HP>50%才能使用。冷却{cd}回合。' },
    ]},
  { id:'hunter',    name:'猎人龟',   emoji:'🏹🐢',    rarity:'A',   hp:339,  atk:43,  def:13, mr:11, spd:15, crit:0.25,
    img:'../../assets/pets/猎人龟v1.png', sprite:{frames:15,frameW:500,frameH:500,duration:1500},
    passive:{ type:'hunterKill', name:'猎杀', hpThresh:18, stealPct:20, lifesteal:10,
              brief:'斩杀生命值低于 <span class="val-atk">18%</span> 的敌人，击杀后窃取属性并获得 <span class="val-heal">生命偷取</span>',
              desc:'猎人龟的猎杀本能。\n\n每次行动后检查，生命值低于 <span class="val-atk">18%</span> 的敌人直接斩杀。\n斩杀或击杀敌人时，窃取对方 <span class="val-atk">20%</span> 基础属性（攻击力/护甲/魔抗/最大生命值），并叠加 <span class="val-heal">10%</span> 生命偷取。\n\n已猎杀 <span class="val-atk">{B:hunterKills}</span> 只敌方\n累计获得：攻击力+{N:hunterStolenAtk} 护甲+{D:hunterStolenDef} 魔抗+{M:hunterStolenMr} 最大生命值+{H:hunterStolenHp} 生命偷取{B:lifesteal}%' },
    skills:[
      { name:'射箭',     type:'hunterShot', hits:3, power:0, pierce:0, cd:0, atkScale:0.5, execThresh:40, execCrit:40, execCritDmg:20,
        brief:'猎人龟射击3段，共（{N:0.5*ATK*3}）物理伤害，目标HP低于40%时额外暴击',
        detail:'猎人龟对单体射击3段，每段造成（50%×攻击力({ATK}) = {N:0.5*ATK}）物理伤害。\n共（150%×攻击力({ATK}) = {N:0.5*ATK*3}）物理伤害。\n目标生命值低于 <span class="val-atk">40%</span> 时，额外获得 <span class="val-atk">+40%</span> 暴击率和 <span class="val-atk">+20%</span> 爆伤。' },
      { name:'隐蔽',     type:'hunterStealth', hits:1, power:0, pierce:0, cd:3, dmgScale:0.9, dodgePct:25, dodgeTurns:3, shieldScale:0.7, shieldTurns:3,
        brief:'猎人龟射一箭造成（{N:0.9*ATK}）物理伤害，获得 <span class="val-atk">25%</span> 闪避3回合 +（{S:0.7*ATK}）护盾',
        detail:'猎人龟对单体射一箭，造成（90%×攻击力({ATK}) = {N:0.9*ATK}）物理伤害。\n获得 <span class="val-atk">25%</span> 闪避率3回合。\n获得（70%×攻击力({ATK}) = {S:0.7*ATK}）护盾。\n冷却{cd}回合。' },
      { name:'连珠箭',   type:'hunterBarrage', dmgType:'true', hits:10, power:0, pierce:0, cd:4, arrowScale:0.20,
        brief:'猎人龟发射10根箭随机射向敌方，每根（{T:0.2*ATK}）真实伤害',
        detail:'猎人龟发射10根箭，随机分布到敌方目标。\n每根造成（20%×攻击力({ATK}) = {T:0.2*ATK}）真实伤害。\n共（200%×攻击力({ATK}) = {T:0.2*ATK*10}）真实伤害。\n冷却{cd}回合。' },
    ]},
  { id:'pirate',    name:'海盗龟',   emoji:'🏴‍☠️🐢',  rarity:'A',   hp:371,  atk:41,  def:15, mr:13, spd:12, crit:0.25,
    img:'../../assets/pets/海盗龟.png',
    passive:{ type:'pirateBarrage', name:'掠夺', bombardPct:25, deathHookPct:25,
              brief:'开局轰击随机敌人 {T:HP*0.25} 真实伤害；死亡时钩锁击杀者 {T:HP*0.25} 真实伤害',
              desc:'海盗龟开局轰击随机敌人 25%×(最大HP={HP}) = {T:HP*0.25} 真实伤害。\n死亡时钩锁击杀者 25%×(最大HP={HP}) = {T:HP*0.25} 真实伤害。' },
    skills:[
      { name:'弯刀',     type:'physical', hits:4, power:0, pierce:0, cd:0, atkScale:0.35,
        brief:'海盗龟打击4段，共 {N:0.35*ATK*4} 物理伤害',
        detail:'海盗龟对单体目标打击4段，每段造成 35%×(攻击力={ATK}) = {N:0.35*ATK} 物理伤害，共 140%×(攻击力={ATK}) = {N:0.35*ATK*4} 物理伤害。' },
      { name:'火炮齐射', type:'pirateCannonBarrage', hits:10, power:0, pierce:0, cd:4, aoe:true, atkScale:0.1, hpPct:1,
        brief:'海盗龟对全体敌方同时开炮，分10段扣血，共 {N:0.1*ATK*10} + 10%目标最大HP 物理伤害',
        detail:'海盗龟对全体敌方同时开炮齐射。\n炮弹命中后分10段持续扣血，每段造成 10%×(攻击力={ATK}) = {N:0.1*ATK} + 1%目标最大HP 物理伤害。\n共 100%×(攻击力={ATK}) = {N:0.1*ATK*10} + 10%目标最大HP 物理伤害。\n冷却{cd}回合。' },
      { name:'朗姆酒',   type:'heal', hits:1, power:0, heal:0, cd:3, selfCast:true, hot:{hpPerTurn:43,turns:4}, defUpAtkPct:{pct:15,turns:3},
        brief:'海盗龟喝朗姆酒，持续回复43HP/回合共4回合，<span class="val-def">护甲</span>+{D:ATK*0.15} 3回合',
        detail:'海盗龟喝朗姆酒，持续回复 43HP/回合 4回合（可叠加），并提升<span class="val-def">护甲</span> 15%×(攻击力={ATK}) = {D:ATK*0.15} 点，持续3回合。\n冷却{cd}回合。' },
    ]},
  { id:'candy',     name:'糖果龟',   emoji:'🍬🐢',    rarity:'A',   hp:360,  atk:40,  def:15, mr:16, spd:12, crit:0.25,
    img:'../../assets/pets/糖果龟v1.png', sprite:{frames:10,frameW:500,frameH:500,duration:1000},
    passive:{ type:'candySteal', stealTurn:3, stealPct:23, desc:'登场3回合后，偷取随机敌人23%最大生命值加给自己（敌人最大HP和当前HP同步减少）' },
    skills:[
      { name:'糖果弹', type:'magic', dmgType:'magic', hits:3, power:0, pierce:0, cd:0, atkScale:0.5, atkDown:{pct:15,turns:2},
        brief:'糖果龟发射3颗糖果弹，共{N:0.5*ATK*3}魔法伤害，减攻15%',
        detail:'糖果龟对单体发射3颗糖果弹。\n每段造成 50%×(攻击力={ATK}) = {N:0.5*ATK} 魔法伤害，共{N:0.5*ATK*3}。\n附加减攻15%持续2回合。' },
      { name:'棉花糖盾', type:'shield', hits:1, power:0, pierce:0, cd:3, shieldAtkScale:0.6, aoeAlly:true,
        brief:'糖果龟为全体友方施加{S:0.6*ATK}护盾',
        detail:'糖果龟用棉花糖为全体友方施加 60%×(攻击力={ATK}) = {S:0.6*ATK} 护盾。\n冷却{cd}回合。' },
      { name:'糖衣炮弹', type:'magic', dmgType:'magic', hits:8, power:0, pierce:0, cd:4, atkScale:0.35, pierceScale:0.1, defDown:{pct:15,turns:2},
        brief:'糖果龟发射8段糖衣炮弹，每段{N:0.35*ATK}魔法+{P:0.1*ATK}真实，减防15%',
        detail:'糖果龟对单体发射8段糖衣炮弹。\n每段造成 35%×(攻击力={ATK}) = {N:0.35*ATK} 魔法 + 10%×(攻击力={ATK}) = {P:0.1*ATK} 真实。\n共 {N:0.35*ATK*8} 魔法 + {P:0.1*ATK*8} 真实。\n附加减防15%持续2回合。\n冷却{cd}回合。' },
    ]},
  { id:'bubble',    name:'泡泡龟',   emoji:'🫧🐢',    rarity:'A',   hp:350,  atk:39,  def:18, mr:19, spd:14, crit:0.25,
    img:'../../assets/pets/气泡龟v1.png', sprite:{frames:8,frameW:500,frameH:500,duration:800},
    passive:{ type:'bubbleStore', name:'泡沫', pct:35, healPct:60,
              brief:'受伤储存 <span class="val-atk">35%</span> 为泡泡值，每回合回复储存值的 <span class="val-heal">60%</span>',
              desc:'泡泡龟受到的伤害储存 <span class="val-atk">35%</span> 为泡泡值。\n每回合回复泡泡值的 <span class="val-heal">60%</span> 生命值，然后清空泡泡值。\n受伤越多，回复越多。' },
    skills:[
      { name:'泡泡盾',   type:'bubbleShield', hits:1, power:0, pierce:0, cd:3, atkScale:2.1, duration:3, burstScale:2.0,
        brief:'泡泡龟为友方施加（{S:2.1*ATK}）泡泡护盾3回合，到期爆炸造成（{M:2.0*ATK}）魔法伤害',
        detail:'泡泡龟为友方单体套上（210%×攻击力({ATK}) = {S:2.1*ATK}）泡泡护盾（与普通护盾独立），持续3回合。\n自然到期（未被打破）时对全体敌方造成（200%×攻击力({ATK}) = {M:2.0*ATK}）魔法伤害。\n冷却{cd}回合。' },
      { name:'泡泡攻击', type:'magic', dmgType:'magic', hits:3, power:0, pierce:0, cd:0, atkScale:0.7,
        brief:'泡泡龟攻击3段，共（{M:0.7*ATK*3}）魔法伤害',
        detail:'泡泡龟对单体攻击3段。\n每段造成（70%×攻击力({ATK}) = {M:0.7*ATK}）魔法伤害。\n共（210%×攻击力({ATK}) = {M:0.7*ATK*3}）魔法伤害。' },
      { name:'泡泡束缚', type:'bubbleBind', hits:1, power:0, pierce:0, cd:5, duration:5, bindPct:55,
        brief:'标记敌方5回合，友方攻击被标记目标获得伤害 <span class="val-atk">55%</span> 的永久护盾',
        detail:'泡泡龟标记敌方单体5回合。\n友方攻击被标记目标时，获得造成伤害× <span class="val-atk">55%</span> 的永久护盾。\n冷却{cd}回合。' },
    ]},
  { id:'line',      name:'线条龟',   emoji:'✏️🐢',    rarity:'A',   hp:318,  atk:47,  def:10, mr:11, spd:16, crit:0.25,
    img:'../../assets/pets/线条龟v1.png', sprite:{frames:14,frameW:500,frameH:500,duration:1400},
    passive:{ type:'inkMark', pctPerStack:5, maxStacks:5, desc:'攻击叠墨迹（上限{maxStacks}层），每层使目标受到所有伤害+{pctPerStack}%，满层+{S:pctPerStack*maxStacks}%' },
    skills:[
      { name:'素描', type:'lineSketch', hits:3, power:0, pierce:0, cd:0, atkScale:0.35,
        brief:'线条龟画出{hits}笔，每笔{N:0.35*ATK}物理伤害，每段叠1层墨迹',
        detail:'线条龟对单体快速画出{hits}笔。\n每笔造成 35%×(攻击力={ATK}) = {N:0.35*ATK} 物理伤害，共 105%×(攻击力={ATK}) = {N:0.35*ATK*3} 物理伤害。\n每段命中叠加1层墨迹（墨迹使目标受到伤害+5%/层，上限5层）。' },
      { name:'连笔', type:'lineLink', hits:1, power:0, pierce:0, cd:3, atkScale:0.5, duration:3, transferPct:30,
        brief:'线条龟连接2个敌人{duration}回合，伤害传递{transferPct}%真实，墨迹共享',
        detail:'线条龟画线连接两个敌人，持续{duration}回合。\n对两个目标各造成 50%×(攻击力={ATK}) = {N:0.5*ATK} 物理伤害，各叠1层墨迹。\n连接期间，一方受到伤害的 {transferPct}% 以真实伤害传递给另一方。\n一方获得墨迹时，另一方也获得相同层数。\n冷却{cd}回合。' },
      { name:'画龙点睛', type:'lineFinish', hits:1, power:0, pierce:0, cd:4, baseScale:0.6, perStackScale:0.4,
        brief:'线条龟引爆目标墨迹，基础{N:0.6*ATK}物理 + 每层墨迹{P:0.4*ATK}真实',
        detail:'线条龟完成最后一笔，引爆目标所有墨迹。\n基础造成 60%×(攻击力={ATK}) = {N:0.6*ATK} 物理伤害。\n每层墨迹额外造成 40%×(攻击力={ATK}) = {P:0.4*ATK} 真实伤害。\n满5层引爆：{N:0.6*ATK} 物理 + {P:0.4*ATK*5} 真实。\n引爆后清除目标所有墨迹。\n冷却{cd}回合。' },
    ]},
  { id:'lightning', name:'闪电龟',   emoji:'⚡🐢',    rarity:'A',   hp:329,  atk:46,  def:10, mr:13, spd:18, crit:0.25,
    img:'../../assets/pets/闪电龟.png',
    passive:{ type:'lightningStorm', name:'雷电', shockScale:0.9, stackMax:8,
              brief:'每回合电击随机敌人 {T:ATK*0.9} 真实伤害；攻击叠电击层，满8层引爆 {T:ATK*0.9} 真实伤害',
              desc:'闪电龟周身环绕雷电之力。\n\n每回合自动电击随机敌人，造成（90%×攻击力({ATK}) = {T:ATK*0.9}）真实伤害。\n\n每段攻击命中敌人叠加1层电击标记，满{stackMax}层时引爆雷暴，\n造成（90%×攻击力({ATK}) = {T:ATK*0.9}）真实伤害并清零层数。' },
    skills:[
      { name:'闪电打击', type:'lightningStrike', dmgType:'magic', hits:5, power:0, pierce:0, cd:0, atkScale:0.23, splashPct:25,
        brief:'闪电龟打击5段，共 {M:0.23*ATK*5} 魔法伤害，每段溅射25%到次目标，每段叠电击层',
        detail:'闪电龟对单体目标打击5段，每段造成（23%×攻击力({ATK}) = {M:0.23*ATK}）魔法伤害。\n共（115%×攻击力({ATK}) = {M:0.23*ATK*5}）魔法伤害。\n每段对次目标造成主目标25%溅射伤害。\n每段命中叠加1层电击标记。' },
      { name:'威力增幅', type:'lightningBuff', hits:1, power:0, pierce:0, cd:4, atkUpPct:20, atkUpTurns:4,
        brief:'闪电龟为全体友方施加 <span class="val-atk">+20%攻击力</span> 提升效果，持续4回合',
        detail:'闪电龟为全体友方施加攻击力提升效果。\n每名友方基于自身攻击力获得 <span class="val-atk">+20%</span> 攻击力加成，持续4回合。\n冷却{cd}回合。' },
      { name:'雷暴',     type:'lightningBarrage', dmgType:'magic', hits:20, power:0, pierce:0, cd:5, arrowScale:0.11,
        brief:'闪电龟释放20次闪电随机命中敌方，每次 {M:0.11*ATK} 魔法伤害，每次叠电击层',
        detail:'闪电龟释放20次闪电，随机分布到敌方目标。\n每次造成（11%×攻击力({ATK}) = {M:0.11*ATK}）魔法伤害。\n每次命中叠加1层电击标记。\n冷却{cd}回合。' },
    ]},
  // S级
  { id:'phoenix',   name:'凤凰龟',   emoji:'🔥🐢',    rarity:'S',   hp:330,  atk:42,  def:12, mr:15, spd:14, crit:0.25,
    img:'../../assets/pets/凤凰龟.png',
    passive:{ type:'phoenixRebirth', name:'涅槃', revivePct:25,
              brief:'凤凰龟首次死亡时浴火重生，以 {H:HP*0.25} HP复活，并对全体敌人施加<span style="color:#ff6600">灼烧</span>与治疗削减',
              desc:'凤凰龟拥有涅槃之力。\n\n首次死亡时浴火重生，以（25%×最大生命值({HP}) = {H:HP*0.25}）HP复活。\n复活后保留所有增益和减益效果。\n并对全体敌人施加<span style="color:#ff6600">灼烧</span>4回合与治疗削减3回合（<span class="val-atk">-50%</span>）。' },
    skills:[
      { name:'灼烧',   type:'phoenixBurn', dmgType:'magic', hits:1, power:0, pierce:0, cd:0, atkScale:0.9,
        brief:'凤凰龟造成（{M:0.9*ATK}）魔法伤害，施加<span style="color:#ff6600">灼烧</span>4回合',
        detail:'凤凰龟对单体造成（90%×攻击力({ATK}) = {M:0.9*ATK}）魔法伤害。\n施加<span style="color:#ff6600">灼烧</span>4回合（每回合40%攻击力+8%最大生命值，魔法伤害）。' },
      { name:'熔岩盾', type:'phoenixShield', hits:1, power:0, pierce:0, cd:4, shieldScale:1.0, duration:4, counterScale:0.16,
        brief:'凤凰龟获得（{S:1.0*ATK}）熔岩护盾4回合，被攻击每段反击（{M:0.16*ATK}）',
        detail:'凤凰龟获得（100%×攻击力({ATK}) = {S:1.0*ATK}）熔岩护盾，持续4回合。\n有护盾时被攻击的每段反击（16%×攻击力({ATK}) = {M:0.16*ATK}）魔法伤害。\n冷却{cd}回合。' },
      { name:'烫伤',   type:'phoenixScald', dmgType:'magic', hits:1, power:0, pierce:0, cd:3, atkScale:0.7, atkDown:{pct:15,turns:3}, defDown:{pct:15,turns:3}, shieldBreak:50,
        brief:'凤凰龟破坏50%护盾，造成（{M:0.7*ATK}）魔法伤害，施加 <span class="val-atk">-15%</span> 攻击力和护甲3回合',
        detail:'凤凰龟对单体施放烫伤。\n先破坏目标50%的护盾值，再造成（70%×攻击力({ATK}) = {M:0.7*ATK}）魔法伤害。\n施加攻击力 <span class="val-atk">-15%</span> 和护甲 <span class="val-atk">-15%</span> 效果，持续3回合。\n冷却{cd}回合。' },
    ]},
  { id:'lava',      name:'熔岩龟',   emoji:'🌋🐢',    rarity:'S',   hp:414,  atk:41,  def:20, mr:17, spd:8, crit:0.25,
    img:'../../assets/pets/熔岩龟.png',
    passive:{ type:'counterAttack', pct:30, desc:'30%概率反击' },
    skills:[
      { name:'熔岩喷发', type:'magic', dmgType:'magic', hits:1, power:0, pierce:0, cd:0, atkScale:0.9, burn:true,
        brief:'熔岩龟造成{N:0.9*ATK}魔法伤害，施加灼烧4回合',
        detail:'熔岩龟对单体造成 90%×(攻击力={ATK}) = {N:0.9*ATK} 魔法伤害。\n施加灼烧4回合（每回合40%ATK+8%最大HP魔法伤害）。' },
      { name:'岩浆护甲', type:'shield', hits:1, power:0, pierce:0, cd:3, shieldAtkScale:0.8, shieldDuration:3,
        brief:'熔岩龟获得{S:0.8*ATK}护盾，持续3回合',
        detail:'熔岩龟获得 80%×(攻击力={ATK}) = {S:0.8*ATK} 护盾，持续3回合。\n冷却{cd}回合。' },
      { name:'火山爆发', type:'magic', dmgType:'magic', hits:5, power:0, pierce:0, cd:4, aoe:true, atkScale:0.14, pierceScale:0.07, burn:true,
        brief:'熔岩龟对全体敌方每人喷发5段，每段{N:0.14*ATK}魔法+{P:0.07*ATK}真实，施加灼烧4回合',
        detail:'熔岩龟对全体敌方每人喷发5段。\n每段造成 14%×(攻击力={ATK}) = {N:0.14*ATK} 魔法 + 7%×ATK = {P:0.07*ATK} 真实。\n施加灼烧4回合（每回合40%ATK+8%最大HP魔法伤害）。\n冷却{cd}回合。' },
    ]},
  { id:'cyber',     name:'赛博龟',   emoji:'🤖🐢',    rarity:'S',   hp:360,  atk:47,  def:14, mr:13, spd:16, crit:0.25,
    img:'../../assets/pets/赛博龟.png',
    passive:{ type:'cyberDrone', droneScale:0.13, droneMaxAge:5, maxDrones:10, mechHpPer:30, mechAtkPer:5,
              desc:'每回合生成1个浮游炮（当前拥有 {B:droneCount} 个，最多拥有10个浮游炮）。\n每个浮游炮每回合对随机敌人造成 {N:ATK*0.13} 物理伤害（13%×攻击力）。\n\n赛博龟阵亡时，所有浮游炮自动组装为机甲，机甲具有：\n生命值 = 30 × 浮游炮数量（当前{B:droneCount}个）= {H:mechHp}\n攻击力 = 5 × 浮游炮数量（当前{B:droneCount}个）= {N:mechAtk}\n防御力 = 0，暴击率 = 25%\n机甲每回合自动攻击血量最低的敌人，造成150%×机甲攻击力 = {N:mechAtk*1.5} 物理伤害。' },
    skills:[
      { name:'激光枪', type:'physical', hits:5, power:0, pierce:0, cd:0, atkScale:0.15, hpPct:2.4,
        brief:'赛博龟发射激光5段，共{N:0.15*ATK*5}物理伤害+12%目标最大HP',
        detail:'赛博龟对单体目标发射激光5段，每段造成 15%×(攻击力={ATK}) = {N:0.15*ATK} + 2.4%目标最大HP 物理伤害，共 75%×(攻击力={ATK}) = {N:0.15*ATK*5} + 12%目标最大HP 物理伤害。' },
      { name:'增益', type:'cyberBuff', hits:1, power:0, pierce:0, cd:3, selfAtkUpPct:{pct:27,turns:4},
        brief:'赛博龟提升自身攻击力{B:ATK*0.27}（27%），持续4回合',
        detail:'赛博龟提升自身攻击力 27%×(攻击力={ATK}) = {B:ATK*0.27}点，持续4回合。\n冷却3回合。' },
      { name:'部署', type:'cyberDeploy', hits:1, power:0, pierce:0, cd:2,
        brief:'赛博龟立即部署1个浮游炮（每回合{N:ATK*0.13}物理伤害，上限10）',
        detail:'赛博龟立即生成1个浮游炮。\n每个浮游炮每回合对随机敌人造成 13%×(攻击力={ATK}) = {N:ATK*0.13} 物理伤害。\n最多持有10个。冷却2回合。' },
    ]},
  { id:'crystal',   name:'水晶龟',   emoji:'🔮🐢',    rarity:'S',   hp:382,  atk:44,  def:21, mr:23, spd:12, crit:0.25,
    img:'../../assets/pets/水晶龟v1.png', sprite:{frames:11,frameW:500,frameH:500,duration:1100},
    passive:{ type:'shieldOnHit', amount:22, desc:'受击时获得22护盾(每回合1次)' },
    skills:[
      { name:'水晶刺', type:'magic', dmgType:'magic', hits:2, power:0, pierce:0, cd:0, atkScale:0.5, pierceScale:0.15,
        brief:'水晶龟刺出2段，每段{N:0.5*ATK}魔法+{P:0.15*ATK}真实',
        detail:'水晶龟对单体刺出2段。\n每段造成 50%×(攻击力={ATK}) = {N:0.5*ATK} 魔法 + 15%×ATK = {P:0.15*ATK} 真实。\n共 {N:0.5*ATK*2} 魔法 + {P:0.15*ATK*2} 真实。' },
      { name:'水晶壁垒', type:'shield', hits:1, power:0, pierce:0, cd:3, shieldAtkScale:0.8, shieldDuration:3,
        brief:'水晶龟获得{S:0.8*ATK}护盾，持续3回合',
        detail:'水晶龟获得 80%×(攻击力={ATK}) = {S:0.8*ATK} 护盾，持续3回合。\n冷却{cd}回合。' },
      { name:'碎晶风暴', type:'magic', dmgType:'magic', hits:7, power:0, pierce:0, cd:4, atkScale:0.16, pierceScale:0.09, burn:true,
        brief:'水晶龟释放7段碎晶，每段{N:0.16*ATK}魔法+{P:0.09*ATK}真实，附加灼烧4回合',
        detail:'水晶龟释放7段碎晶风暴。\n每段造成 16%×ATK = {N:0.16*ATK} 魔法 + 9%×ATK = {P:0.09*ATK} 真实。\n共 {N:0.16*ATK*7} 魔法 + {P:0.09*ATK*7} 真实。\n附加灼烧4回合（每回合40%ATK+8%最大HP魔法伤害）。\n冷却{cd}回合。' },
    ]},
  { id:'chest',     name:'宝箱龟',   emoji:'📦🐢',    rarity:'S',   hp:345,  atk:40,  def:16, mr:14, spd:10, crit:0.25,
    img:'../../assets/pets/宝箱龟v1.png', sprite:{frames:11,frameW:300,frameH:200,duration:1100},
    passive:{ type:'chestTreasure', name:'藏宝图',
              thresholds:[50, 120, 220, 350, 500],
              pools:[
                // 基础池 (tier 0-1)
                [
                  { id:'blade',  icon:'equip-blade-icon.png', name:'锋利短刃',   desc:'<span class="val-normal">攻击力</span> <span class="val-atk">+25%</span>', stat:'atk', pct:25 },
                  { id:'shield', icon:'equip-shield-icon.png', name:'坚固木盾',   desc:'<span class="val-def">护甲</span>/<span class="val-magic">魔抗</span> <span class="val-atk">+20%</span>', stat:'defMr', pct:20 },
                  { id:'rum',    icon:'equip-rum-icon.png', name:'海盗龟的小瓶朗姆酒', desc:'每回合回复 <span class="val-heal">6%</span> <span class="val-heal">最大生命值</span>', stat:'hot', pct:6 },
                  { id:'dice',   icon:'gambler-blood-icon.png', name:'骰子龟的血筛子', desc:'暴击率 <span class="val-atk">+35%</span>', stat:'crit', pct:35 },
                  { id:'chain',  icon:'equip-chain-icon.png', name:'锁链',   desc:'「宝箱砸击」连锁：对次要目标造成25%伤害', stat:'chain', pct:25 },
                  { id:'rock',   icon:'equip-rock-icon.png', name:'神奇石头',   desc:'「宝箱砸击」伤害额外加成70%<span class="val-def">护甲</span>+70%<span class="val-magic">魔抗</span>', stat:'rock', pct:70 },
                ],
                // 进阶池 (tier 2-3)
                [
                  { id:'sword',  icon:'equip-sword-icon.png', name:'精钢长剑',   desc:'<span class="val-normal">攻击力</span> <span class="val-atk">+45%</span>', stat:'atk', pct:45 },
                  { id:'vamp',   icon:'equip-vamp-icon.png', name:'嗜血之刃', desc:'<span class="val-heal">生命偷取</span> <span class="val-heal">+25%</span>', stat:'lifesteal', pct:25 },
                  { id:'fire',   icon:'equip-fire-icon.png', name:'灼热火石',   desc:'造成伤害后对被命中目标施加<span style="color:#ff6600">灼烧</span>', stat:'burn' },
                  { id:'gem',    icon:'equip-gem-icon.png', name:'宝石铠甲', desc:'<span class="val-def">护甲</span>/<span class="val-magic">魔抗</span> <span class="val-atk">+25%</span>，<span class="val-heal">最大生命值</span> <span class="val-heal">+60</span>', stat:'defMr', pct:25, bonusHp:60 },
                  { id:'poison', icon:'equip-poison-icon.png', name:'淬毒箭矢',   desc:'造成伤害后对被命中目标施加治疗削减3回合（<span class="val-atk">-50%</span>）', stat:'healReduce' },
                  { id:'phoenix',icon:'equip-phoenix-icon.png', name:'凤凰龟雕像',desc:'首次死亡时以 <span class="val-heal">25%</span> <span class="val-heal">最大生命值</span>重生', stat:'revive', pct:25 },
                ],
                // 传说池 (tier 4)
                [
                  { id:'crown',  icon:'equip-crown-icon.png', name:'王者之冠',   desc:'<span class="val-normal">攻击力</span> <span class="val-atk">+40%</span>，暴击 <span class="val-atk">+40%</span>，<span class="val-atk">爆伤</span> <span class="val-atk">+25%</span>，<span class="val-heal">生命偷取</span> <span class="val-heal">+15%</span>', stat:'crown' },
                  { id:'thunder',icon:'lightning-storm-icon.png', name:'闪电龟的雷刃',   desc:'「宝箱砸击」和「财宝风暴」命中叠金闪电层，满8层引爆100%ATK <span class="val-true">真实伤害</span>', stat:'thunder' },
                  { id:'star',   icon:'equip-star-icon.png', name:'星际龟的星辉',   desc:'所有伤害转为 <span class="val-true">真实伤害</span>', stat:'trueDmg' },
                ],
              ],
              brief:'宝箱龟会根据造成的伤害获得财宝进度，从战利品池中获得各种强力装备',
              desc:'宝箱龟会根据造成的伤害获得财宝进度，从战利品池中获得各种强力装备。\n\n造成伤害积累财宝值，达到阈值时随机抽取装备：\n第1-2件：基础池（短刃/木盾/朗姆酒/血筛子/铁链/石头）\n第3-4件：进阶池（长剑/吸血刀/火石/宝石甲/毒箭/凤凰雕像）\n第5件：传说池（王冠/雷刃/星辉）\n\n阈值：80 / 180 / 300 / 450 / 650' },
    skills:[
      { name:'宝箱砸击', type:'chestSmash', hits:4, power:0, pierce:0, cd:0, atkScale:1.6,
        brief:'_chestSmashBrief_',
        detail:'_chestSmashDetail_' },
      { name:'清点财宝', type:'chestCount', hits:1, power:0, pierce:0, cd:4, healPct:15, shieldAtkScale:0.7,
        brief:'宝箱龟回复 {H:HP*0.15} HP + {S:0.7*ATK} 护盾，每100点财宝值强度+14%',
        detail:'宝箱龟清点财宝，回复（15%×最大生命值({HP}) = {H:HP*0.15}）HP。\n获得（70%×攻击力({ATK}) = {S:0.7*ATK}）护盾。\n每拥有100点财宝值，技能强度增加 <span class="val-atk">14%</span>。\n冷却{cd}回合。' },
      { name:'财宝风暴', type:'chestStorm', hits:10, power:0, pierce:0, cd:4, aoe:true, atkScale:0.09, pierceScale:0.04,
        brief:'宝箱龟对每个敌人飞射10段，每段（{N:0.09*ATK}）物理+（{T:0.04*ATK}）真实',
        detail:'宝箱龟对每个敌人飞射10段财宝。\n每段造成（9%×攻击力({ATK}) = {N:0.09*ATK}）物理 +（4%×攻击力({ATK}) = {T:0.04*ATK}）真实伤害。\n共（{N:0.09*ATK*10}）物理 +（{T:0.04*ATK*10}）真实伤害（每个敌人）。\n冷却{cd}回合。' },
    ]},
  { id:'space',     name:'星际龟',   emoji:'🚀🐢',    rarity:'S',   hp:349,  atk:48,  def:13, mr:15, spd:17, crit:0.25,
    img:'../../assets/pets/星际龟v1.png', sprite:{frames:12,frameW:500,frameH:500,duration:1200},
    passive:{ type:'starEnergy', chargeRate:80, maxChargePct:50,
              desc:'造成伤害积累星能（伤害的80%），上限 {B:HP*0.5}（50%最大HP），满能时下次攻击附加等量{P:真实爆发}' },
    skills:[
      { name:'星光射线', type:'starBeam', dmgType:'magic', hits:3, power:0, pierce:0, cd:0, atkScale:0.4, currentHpPct:5,
        brief:'星际龟发射3段共{N:0.4*ATK*3}+15%目标当前HP魔法伤害，积累星能',
        detail:'星际龟对单体发射3段，每段 40%×(攻击力={ATK}) = {N:0.4*ATK} + 5%目标当前HP 魔法伤害。\n共 120%×(攻击力={ATK}) = {N:0.4*ATK*3} + 15%目标当前HP。\n每段伤害的20%转为星能。' },
      { name:'虫洞', type:'starWormhole', hits:1, power:0, pierce:0, cd:3, pierceBonusPct:30, normalBonusPct:15, duration:3,
        brief:'标记敌人3回合：受到真实+30%，星际龟魔伤+15%',
        detail:'星际龟对敌方单体施加虫洞标记3回合。\n被标记目标受到的所有真实伤害+{B:30}%。\n星际龟对该目标的魔法伤害+{B:15}%。\n冷却3回合。' },
      { name:'流星暴击', type:'starMeteor', dmgType:'magic', hits:1, power:0, pierce:0, cd:4, atkScale:1.0, aoe:true, energyReadPct:50, defDown:{pct:20,turns:3},
        brief:'全体敌方{N:ATK}魔法 + 50%星能值真实（不消耗），减防20%',
        detail:'星际龟对全体敌方造成 100%×(攻击力={ATK}) = {N:ATK} 魔法伤害。\n附加当前星能50%的真实伤害（每人全额，不消耗星能）。\n施加防御-20% 3回合。\n冷却4回合。' },
    ]},
  // SS级
  { id:'hiding',    name:'缩头乌龟', emoji:'🫣🐢',    rarity:'SS',  hp:426,  atk:39,  def:25, mr:24, spd:6, crit:0.25,
    img:'../../assets/pets/缩头乌龟v1.png', sprite:{frames:14,frameW:500,frameH:500,duration:1400},
    passive:{ type:'summonAlly', hpPct:40, maxRarity:'A',
              desc:'开局召唤一只A级以下龟(40%HP，属性/被动正常)，攻击后随从自动出招' },
    skills:[
      { name:'防御', type:'hidingDefend', hits:1, power:0, pierce:0, cd:3, shieldHpPct:20, shieldDuration:4, shieldHealPct:20,
        brief:'缩头乌龟获得{S:HP*0.2}护盾持续{shieldDuration}回合，到期回收剩余盾{shieldHealPct}%为HP',
        detail:'缩头乌龟获得 20%×(最大HP={HP}) = {S:HP*0.2} 护盾，持续{shieldDuration}回合。\n到期时将剩余护盾值的{shieldHealPct}%转化为HP回复。\n冷却{cd}回合。' },
      { name:'攻击', type:'physical', hits:1, power:0, pierce:0, cd:0, atkScale:1.0, selfDefUpPct:{pct:20,turns:2},
        brief:'缩头乌龟造成{N:atkScale*ATK}物理伤害，自身防御+{B:DEF*0.2}（20%）持续2回合',
        detail:'缩头乌龟对单体目标造成 100%×(攻击力={ATK}) = {N:atkScale*ATK} 物理伤害。\n自身防御提升 20%×(防御={DEF}) = {B:DEF*0.2}点，持续2回合。' },
      { name:'指挥', type:'hidingCommand', hits:1, power:0, pierce:0, cd:2,
        brief:'缩头乌龟命令随从出击，随从释放2次随机技能',
        detail:'缩头乌龟命令随从立即释放一个随机可用技能。\n回合结束后随从再自动释放一个（共2次出手）。\n如果随从已阵亡则无效。冷却{cd}回合。' },
    ]},
  { id:'headless',  name:'无头龟',   emoji:'💀🐢',    rarity:'SS',  hp:381,  atk:52,  def:11, mr:9, spd:16, crit:0.25,
    img:'../../assets/pets/无头龟v1.png', sprite:{frames:17,frameW:500,frameH:500,duration:1700},
    passive:{ type:'deathExplode', pct:60, desc:'死亡时对击杀者造成 60%×(最大HP={HP}) = {N:HP*0.6} 伤害' },
    skills:[
      { name:'撕咬',   type:'physical', hits:2, power:0, pierce:0, cd:0, atkScale:0.5, hpPct:6,
        brief:'无头龟撕咬2段，共{N:0.5*ATK*2}物理伤害+{hpPct}%×2目标最大HP',
        detail:'每段造成 50%×(攻击力={ATK}) = {N:0.5*ATK} + {hpPct}%目标最大HP 物理伤害 × 2段' },
      { name:'恐吓',   type:'twoHeadFear', hits:1, power:0, pierce:0, cd:3, atkScale:1.1, fearTurns:3, fearReduction:30,
        brief:'无头龟造成{N:atkScale*ATK}物理伤害，施加恐惧{fearTurns}回合（对无头龟伤害-{fearReduction}%）',
        detail:'无头龟对单体目标造成 110%×(攻击力={ATK}) = {N:atkScale*ATK} 物理伤害。\n施加恐惧{fearTurns}回合：被恐惧目标对无头龟的物理伤害减少 {fearReduction}%（真实伤害除外）。\n冷却{cd}回合。' },
      { name:'窃取',   type:'twoHeadSteal', hits:1, power:0, pierce:0, cd:4,
        brief:'无头龟窃取敌方目标一个随机技能并立即释放',
        detail:'无头龟窃取敌方单体目标的随机一个可用技能并立即以无头龟的属性释放。\n冷却{cd}回合。' },
    ]},
  // SSS级
  { id:'shell',     name:'龟壳',     emoji:'🐚',      rarity:'SSS', hp:414,  atk:48,  def:21, mr:21, spd:14, crit:0.25,
    img:'../../assets/pets/龟壳v1.png', sprite:{frames:20,frameW:500,frameH:500,duration:2000},
    passive:{ type:'auraAwaken',
              awakenTurn:4,
              atkPct:12, defPct:12, hpPct:12,
              lifestealPct:12, reflectPct:12, armorPenPct:12,
              energyStore:true, energyReleaseTurn:4,
              energyDmgScale:0.008, energyShieldScale:0.01, energyShieldTurns:3,
              desc:'6回合后全面强化+10%；受伤储能，每9回合波击释放' },
    skills:[
      { name:'攻击', type:'shellStrike', hits:6, power:0, pierce:0, cd:0, totalScale:1.2, splashPct:25,
        brief:'龟壳打击6段物理/真实交替，共{N:1.2*ATK}混合伤害，每段溅射{splashPct}%',
        detail:'龟壳对单体打击6段，奇数段物理伤害，偶数段真实伤害。\n共 120%×(攻击力={ATK}) = {N:1.2*ATK} 混合伤害。\n每段对次目标溅射主目标{splashPct}%伤害。' },
      { name:'复制', type:'shellCopy', hits:0, power:0, pierce:0, cd:4,
        brief:'龟壳随机复制敌方2个技能并以60%效果释放',
        detail:'龟壳随机复制敌方的2个可用技能，并以60%效果立即释放。\n冷却{cd}回合。' },
    ]},
];

const RARITY_COLORS = { C:'#06d6a0', B:'#4cc9f0', A:'#3a9abf', S:'#c77dff', SS:'#ffd93d', SSS:'#ff6b6b' };

